name: medical_warehouse
version: '1.0.0'
profile: medical_warehouse

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_warehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
