medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "1234"
      port: 5434
      dbname: medical_dw
      schema: analytics
      threads: 4
